## Example 2-03. Quantizing counts with fixed-width bins

In [3]:
import numpy as np

In [4]:
# Generate 20 random integers uniformly between 0 and 99 
small_counts = np.random.randint(0, 100, 20) 
small_counts

array([67, 79, 77, 39, 74, 73, 43, 39,  2, 48, 98, 82, 48, 39, 79, 55,  8,
       83, 65, 70])

In [5]:
# Map to evenly spaced bins 0-9 by division 
np.floor_divide(small_counts, 10)

array([6, 7, 7, 3, 7, 7, 4, 3, 0, 4, 9, 8, 4, 3, 7, 5, 0, 8, 6, 7],
      dtype=int32)

In [6]:
# An array of counts that span several magnitudes
large_counts = [296, 8286, 64011, 80, 3, 725, 867, 2215, 7689, 11495, 91897, 44, 28, 7971, 926, 122, 22222] 

# Map to exponential-width bins via the log function 
np.floor(np.log10(large_counts))

array([2., 3., 4., 1., 0., 2., 2., 3., 3., 4., 4., 1., 1., 3., 2., 2., 4.])

## Example 2-5. Binning counts by quantiles

In [7]:
import pandas as pd

In [8]:
# Map the counts to quartiles
pd.qcut(large_counts, 4, labels=False)

array([1, 2, 3, 0, 0, 1, 1, 2, 2, 3, 3, 0, 0, 2, 1, 0, 3], dtype=int64)

In [10]:
# Compute the quantiles themselves
large_counts_series = pd.Series(large_counts) 
large_counts_series.quantile([0.25, 0.5, 0.75]) 

0.25     122.0
0.50     926.0
0.75    8286.0
dtype: float64